syntax = "proto3";

package phonebook;

service PhonebookService {
  rpc AddContact(AddContactRequest) returns (OperationStatus);
  rpc LookupContact(LookupContactRequest) returns (LookupContactResponse);
  rpc ListContacts(Empty) returns (ListContactsResponse);
}

message Empty {}

message Contact {
  string name = 1;
  string phone = 2;
}

message AddContactRequest {
  string name = 1;
  string phone = 2;
}

message LookupContactRequest {
  string name = 1;
}

message OperationStatus {
  bool success = 1;
  string message = 2;
}

message LookupContactResponse {
  bool success = 1;
  string message = 2;
  Contact contact = 3;
  string signature = 4;
}

message ListContactsResponse {
  repeated Contact contacts = 1;
  string signature = 2;
}
